DensityAwareHerdNetLoss:
  print_name: 'density_focal_loss'
  from_torch: False
  output_idx: 0
  target_idx: 0
  lambda_const: 1.0
  kwargs:
    alpha: 2
    beta: 4
    density_radius: 100
    min_weight: 0.5
    max_weight: 3.0
    density_scale: 'inverse_sqrt'

CrossEntropyLoss:
  print_name: 'ce_loss'
  from_torch: True
  output_idx: 1
  target_idx: 1
  lambda_const: 1.0
  background_class_weight: 0.1
  kwargs:
    reduction: 'mean'
    weight:
      - ${losses.CrossEntropyLoss.background_class_weight}
      - 5.0  # iguana
