
wandb_project: 'herdnet'
wandb_entity: 'karisu'
wandb_run: 'augmentation_dr4_full_size_crop'
wandb_tags: ['iguana','augmentation', 'iguana', 'dla34', 'dr4', 'train_full', 'val_full', 'more_augmentation']
# /home/cwinkelmann/work/software-data-engineering-mac/data/ISAID/
seed: 1
device_name: 'cuda:1'

model:
  name: 'HerdNet'
  # work_dir: "./outputs/"
  from_torchvision: False
  # load_from: '/home/cwinkelmann/work/Herdnet/data/models/20250612_ig_train_down_ratio4_geospatial_val_pix4d_2025_06_11_dla_RUN_9qyfyj4k_r96_p12.pth'
  # load_from: '/home/cwinkelmann/work/HerdNet/tools/outputs/20250611_ig_train_geospatial_val_pix4d_2025_06_11_dla_RUN_qcfixu05.pth'
  # load_from: /raid/cwinkelmann/herdnet/outputs/2025-07-28/16-37-18/best_model.pth # dr2 dataleak, 100% 512px
  # load_from: /raid/cwinkelmann/herdnet/outputs/2025-07-28/16-20-01/best_model.pth

  load_from: /home/cwinkelmann/work/Herdnet/data/models/20250722_bird_weinstein_dr4_edge_512_eoozwrmh.pth
  # resume_from: "/home/cwinkelmann/work/HerdNet/tools/outputs/2025-02-26/15-29-43/latest_model.pth"
  resume_from: null
  kwargs:
    num_layers: 34
    # backbone: 'dla'
    pretrained: True
    down_ratio: 4  # was two before
    head_conv: 64 # was 64
  freeze: null

losses:
  FocalLoss:
    print_name: 'focal_loss'
    from_torch: False
    output_idx: 0
    target_idx: 0
    lambda_const: 1.0
    kwargs:
      reduction: 'mean'
      normalize: False

  CrossEntropyLoss:
    print_name: 'ce_loss'
    from_torch: True
    output_idx: 1
    target_idx: 1
    lambda_const: 1.0
    kwargs:
      reduction: 'mean'
      weight: [2.0,   # 1 # iguana
               5.,    # 2 # hard negative
               15.,   # 3
               1.,    # 4
               0.1,   # 5
               0.1,   # 6
               1.0,   # 7
               0.1    # 8 # background
      ] # One weight for each class including the background
      #weight: [0.9, 0.001, 1.0] # From the notebook

datasets:
  img_size: [512, 512]
  anno_type: 'point'
  num_classes: 8 # One class more for the background
  collate_fn: null

  class_def:
    1: 'iguana'
    2: 'hard_negative' # these next 6 are just there so I can use the pretrained model
    3: 'Kob'
    4: 'Warthog'
    5: 'Waterbuck'
    6: 'Elephant'
    7: 'Impala'

  train:
    # name: 'CSVDataset'
    name: 'CSVDataset'

#    csv_file: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/herdnet_format.csv'
#    root_dir: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/Default'

#    csv_file: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/herdnet_format_512_0_crops.csv'
#    root_dir: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/crops_512_numNone_overlap0'

    csv_file: '/home/cwinkelmann/work/Herdnet/data/floreana_all/val/herdnet_format.csv'
    root_dir: '/home/cwinkelmann/work/Herdnet/data/floreana_all/val/Default'

#    csv_file: '/home/cwinkelmann/work/Herdnet/data/floreana_sample/train/herdnet_format_512_0_crops.csv'
#    root_dir: '/home/cwinkelmann/work/Herdnet/data/floreana_sample/train/crops_512_numNone_overlap0'

    sampler: null
    augmentation_multiplier: 3

    albu_transforms:
      CenterCrop:
        height: 2000
        width: 3000
        p: 1.0
#      PadIfNeeded:
#        min_height: 512
#        min_width: 512
#        always_apply: True
#        border_mode: 4
#        p: 1.0
      ObjectAwareRandomCrop:
        height: 1000
        width: 1000
        p: 1.0
        attempts: 10
        empty_probability: 0.05
      Rotate:
        limit: 145
        p: 0.5
      RandomScale:
        scale_limit: [ 0.9, 1.1 ]
        p: 0.5
#
#      # TODO check if these are beneficial
#      ShiftScaleRotate:
#        shift_limit: 0.1
#        scale_limit: 0.15
#        rotate_limit: 45
#        p: 0.5
#        border_mode: 4
      Perspective:
        scale: [ 0.05, 0.15 ]
        p: 0.3
#      Affine:
#        scale: [ 0.9, 1.1 ]
#        translate_percent: [ 0.1, 0.1 ]
#        rotate: [ -45, 45 ]
#        shear: [ -10, 10 ]
#        p: 0.2

      HorizontalFlip:
        p: 0.2
      VerticalFlip:
        p: 0.2
      MotionBlur:
        p: 0.2
#      RandomRotate90:
#        p: 0.5
      RandomBrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.1
      Blur:
        blur_limit: 5
        p: 0.1
      ToGray:
        p: 0.1



#
      ObjectAwareRandomCropEdgeBlackout:
        height: 512
        width: 512
        p: 1.0
        attempts: 10
        edge_black_blobs: True

      PasspartoutAugmentation:
        p: 1.0
        intensity: 1.0
        gaussian_sigma_ratio: 0.2
        keypoint_threshold: 0.2
        randomize_center: False
        randomize_radius: False

#      RandomCrop:
#        height: 512
#        width: 512
#        p: 1.0
      Normalize:
        p: 1.0


    end_transforms:
      MultiTransformsWrapper:
        FIDT:
          num_classes: ${datasets.num_classes}
          down_ratio: ${model.kwargs.down_ratio}
#          alpha: 0.01
#          beta: 0.5
#          c: 0.1

        PointsToMask:
          radius: 2
          num_classes: ${datasets.num_classes}
          squeeze: True
          down_ratio: 32

  validate:
    name: 'CSVDataset'

#    csv_file: '/home/cwinkelmann/work/Herdnet/data/floreana_all/val/herdnet_format.csv'
#    root_dir: '/home/cwinkelmann/work/Herdnet/data/floreana_all/val/Default'

#    csv_file: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/herdnet_format_512_0_crops.csv'
#    root_dir: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/crops_512_numNone_overlap0'

    csv_file: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/herdnet_format_1024_400_crops.csv'
    root_dir: '/home/cwinkelmann/work/Herdnet/data/floreana_all/train/crops_1024_numNone_overlap400'


# data/FLPC01-07_orthomosaic_herdnet/jpg_tiles
    albu_transforms:
      Normalize:
        p: 1.0

    end_transforms:
      DownSample:
        down_ratio: ${model.kwargs.down_ratio}
        anno_type: ${datasets.anno_type}

training_settings:
  trainer: 'Trainer'
  epochs: 200
  valid_freq: 200
  print_freq: 100
  batch_size: 25
  # optimizer: 'SGD'
  optimizer: 'adamW'
  lr: 1e-3
  weight_decay: 0.0005
  num_workers: 12
  auto_lr:
    mode: 'max'
    patience: 50
    threshold: 1e-4
    threshold_mode: 'rel'
    cooldown: 20
    min_lr: 1e-6
    verbose: True
  warmup_iters: 1000

  # vizual_fn: "model_vizual"
  vizual_fn: visualize_sample
  visualiser:
    name: 'HeatMapVisualizer'
    output_dir: /home/cwinkelmann/work/Herdnet/playground/visualizations/transformed_training_data

  evaluator:
    name: 'HerdNetEvaluator'
    threshold: 25
    select_mode: 'max'
    validate_on: 'f1_score'
    kwargs:
      print_freq: 250
      lmds_kwargs:
        kernel_size: [9, 9]
        adapt_ts: 0.3

  stitcher:
    name: 'HerdNetStitcher'
    kwargs:
      overlap: 120
      down_ratio: ${model.kwargs.down_ratio}
      up: False
      reduction: 'mean'

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

